### ISSUE TITLE
pinkie tool not work this mod

### ISSUE THREAD

**Issue by BigSlammu** [Witch-hue/Akalath-Quarantine-Guide#1]

**Comment by Witch-hue** [comment]
You need to be more descriptive. 

The module is 100% working for calli's proxy. 

Telling me it 'does not work' without giving any discripters does not help.

Error message? ect? Anything. 
I have no way of knowing if its a mod issue, or a you issue. or even a compatibility issue without information.

**Comment by pepsimemen** [comment]
17:03:37 Error: [tera-proxy-game] ReferenceError: FirstMsg is not defined
    at new Tera_Guide (C:\Users\r\Desktop\pp\tera-proxy-betaa\mods\Akalath-Quarantine-Guide-master\index.js:47:22)
    at new ModWrapper (C:\Users\r\Desktop\pp\tera-proxy-betaa\node_modules\tera-proxy-game\connection\dispatch\wrapper.js:134:24)
    at Dispatch.load (C:\Users\r\Desktop\pp\tera-proxy-betaa\node_modules\tera-proxy-game\connection\dispatch\index.js:160:16)
    at Dispatch.loadAll (C:\Users\r\Desktop\pp\tera-proxy-betaa\node_modules\tera-proxy-game\connection\dispatch\index.js:135:65)
    at Dispatch.<anonymous> (C:\Users\r\Desktop\pp\tera-proxy-betaa\bin\cli\index.js:133:14)
    at Object.onceWrapper (events.js:299:28)
    at Dispatch.emit (events.js:210:5)
    at Dispatch.setProtocolVersion (C:\Users\r\Desktop\pp\tera-proxy-betaa\node_modules\tera-proxy-game\connection\dispatch\index.js:338:9)
    at Dispatch.handle (C:\Users\r\Desktop\pp\tera-proxy-betaa\node_modules\tera-proxy-game\connection\dispatch\index.js:405:15)
    at Packetizer.callback (C:\Users\r\Desktop\pp\tera-proxy-betaa\node_modules\tera-proxy-game\clients\RealClient.js:10:65)

thats the error on pinkie proxy if you need
